-- Inicio dos daddos da tabela `classificacoes` --
LOCK TABLES `classificacoes` WRITE;
/*!40000 ALTER TABLE `classificacoes` DISABLE KEYS */;
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (1, 'Neuropática', 1, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (2, 'Isquêmica', 1, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (3, 'Venosa', 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (4, 'Arterial', 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (5, 'Mista', 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (6, 'Lesão por Pressão', 3, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (7, 'Lesão por Queimadura', 4, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (8, 'Curativo Cirúrgico', 5, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (9, 'Deiscência', 5, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `classificacoes` (`id`, `nome`, `lesao_id`, `created`, `modified`) VALUES  (10, 'Infecção Local', 5, '2016-09-17 01:21:38', NULL);
/*!40000 ALTER TABLE `classificacoes` ENABLE KEYS */;
UNLOCK TABLES;
-- Fim dos daddos da tabela `classificacoes` --


-- Inicio dos daddos da tabela `estagios` --
LOCK TABLES `estagios` WRITE;
/*!40000 ALTER TABLE `estagios` DISABLE KEYS */;
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (1, '0', 'Pé de alto risco, sem úlcera, pele integra', 0, 1, 1, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (2, '1', 'Úlcera superficaial, chegando até subcutâneo', 1, 1, 1, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (3, '2', 'Úlcera profunda, sem envolvimento ósseo', 2, 1, 1, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (4, '3', 'Úlcera profunda, com formção de abscesso ou envolvimento ósseo', 3, 1, 1, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (5, '4', 'Gangrena parcial, ou localizada', 4, 1, 1, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (6, '5', 'Gangrena externa, ou de todo pé', 5, 1, 1, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (7, '0', 'Pé de alto risco, sem úlcera, pele integra', 0, 1, 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (8, '1', 'Úlcera superficaial, chegando até subcutâneo', 1, 1, 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (9, '2', 'Úlcera profunda, sem envolvimento ósseo', 2, 1, 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (10, '3', 'Úlcera profunda, com formção de abscesso ou envolvimento ósseo', 3, 1, 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (11, '4', 'Gangrena parcial, ou localizada', 4, 1, 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (12, '5', 'Gangrena externa, ou de todo pé', 5, 1, 2, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (13, '1', 'Aguardar', 1, 2, 3, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (14, '1', 'Aguardar', 1, 2, 4, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (15, '1', 'Aguardar', 1, 2, 5, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (16, 'I', 'Comprometimnento da epiderme', 1, 3, 6, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (17, 'II', 'Comprometimento até a derme', 2, 3, 6, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (18, 'III', 'Comprometimento até o subcutâneo', 3, 3, 6, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (19, 'IV', 'Comprometimento do músculo e tecido adjacente', 4, 3, 6, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (20, '1', 'Superficial (1º grau)', 1, 4, 7, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (21, '2', 'Parcial (2º grau)', 2, 4, 7, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (22, '3', 'Totasl (3º grau)', 3, 4, 7, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (23, '1', 'Sem comprometimento', 0, 5, 8, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (24, 'I', 'Comprometimento da epiderme', 1, 5, 9, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (25, 'II', 'Comprometimento até a derme', 2, 5, 9, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (26, 'III', 'Comprometimento até o subcutâneo', 3, 5, 9, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (27, 'IV', 'Comprometimento do músculo e tecido adjacente', 4, 5, 9, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `estagios` (`id`, `codigo`, `nome`, `peso`, `lesao_id`, `classificacao_id`, `created`, `modified`) VALUES  (28, '1', 'Infecção local', 1, 5, 10, '2016-09-17 01:21:38', NULL);
/*!40000 ALTER TABLE `estagios` ENABLE KEYS */;
UNLOCK TABLES;
-- Fim dos daddos da tabela `estagios` --


-- Inicio dos daddos da tabela `lesoes` --
LOCK TABLES `lesoes` WRITE;
/*!40000 ALTER TABLE `lesoes` DISABLE KEYS */;
INSERT IGNORE INTO `lesoes` (`id`, `nome`, `created`, `modified`) VALUES  (1, 'Pé Diabético', '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `lesoes` (`id`, `nome`, `created`, `modified`) VALUES  (2, 'Lesão de Perna', '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `lesoes` (`id`, `nome`, `created`, `modified`) VALUES  (3, 'Lesão por Pressão', '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `lesoes` (`id`, `nome`, `created`, `modified`) VALUES  (4, 'Lesão por Queimadura', '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `lesoes` (`id`, `nome`, `created`, `modified`) VALUES  (5, 'Lesão Cirúrgica', '2016-09-17 01:21:38', NULL);
/*!40000 ALTER TABLE `lesoes` ENABLE KEYS */;
UNLOCK TABLES;
-- Fim dos daddos da tabela `lesoes` --


-- Inicio dos daddos da tabela `menus` --
LOCK TABLES `menus` WRITE;
/*!40000 ALTER TABLE `menus` DISABLE KEYS */;
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (1, 'Lesoes', NULL, 'Lesoes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (2, 'edit', NULL, 'Lesoes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (3, 'add', NULL, 'Lesoes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (4, 'delete', NULL, 'Lesoes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (5, 'Estados Civis', NULL, 'EstadosCivis', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (6, 'edit', NULL, 'EstadosCivis', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (7, 'add', NULL, 'EstadosCivis', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (8, 'delete', NULL, 'EstadosCivis', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (9, 'Nacionalidades', NULL, 'Nacionalidades', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (10, 'edit', NULL, 'Nacionalidades', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (11, 'add', NULL, 'Nacionalidades', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (12, 'delete', NULL, 'Nacionalidades', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (13, 'Escolaridades', NULL, 'Escolaridades', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (14, 'edit', NULL, 'Escolaridades', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (15, 'add', NULL, 'Escolaridades', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (16, 'delete', NULL, 'Escolaridades', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (17, 'Convenios', NULL, 'Convenios', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (18, 'edit', NULL, 'Convenios', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (19, 'add', NULL, 'Convenios', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (20, 'delete', NULL, 'Convenios', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (21, 'Corporais Lesoes', NULL, 'CorporaisLesoes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (22, 'edit', NULL, 'CorporaisLesoes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (23, 'add', NULL, 'CorporaisLesoes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (24, 'delete', NULL, 'CorporaisLesoes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (25, 'Tabelas Valores Historicos', NULL, 'TabelasValoresHistoricos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (26, 'edit', NULL, 'TabelasValoresHistoricos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (27, 'add', NULL, 'TabelasValoresHistoricos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (28, 'delete', NULL, 'TabelasValoresHistoricos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (29, 'Contatos Tipos', NULL, 'ContatosTipos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (30, 'edit', NULL, 'ContatosTipos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (31, 'add', NULL, 'ContatosTipos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (32, 'delete', NULL, 'ContatosTipos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (33, 'Religioes', NULL, 'Religioes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (34, 'edit', NULL, 'Religioes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (35, 'add', NULL, 'Religioes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (36, 'delete', NULL, 'Religioes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (37, 'Pacientes Soube', NULL, 'PacientesSoube', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (38, 'edit', NULL, 'PacientesSoube', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (39, 'add', NULL, 'PacientesSoube', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (40, 'delete', NULL, 'PacientesSoube', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (41, 'Corporais', NULL, 'Corporais', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (42, 'edit', NULL, 'Corporais', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (43, 'add', NULL, 'Corporais', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (44, 'delete', NULL, 'Corporais', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (45, 'Funcionarios', NULL, 'Funcionarios', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (46, 'edit', NULL, 'Funcionarios', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (47, 'add', NULL, 'Funcionarios', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (48, 'delete', NULL, 'Funcionarios', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (49, 'Parentescos', NULL, 'Parentescos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (50, 'edit', NULL, 'Parentescos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (51, 'add', NULL, 'Parentescos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (52, 'delete', NULL, 'Parentescos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (53, 'Cores', NULL, 'Cores', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (54, 'edit', NULL, 'Cores', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (55, 'add', NULL, 'Cores', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (56, 'delete', NULL, 'Cores', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (57, 'Estagios', NULL, 'Estagios', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (58, 'edit', NULL, 'Estagios', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (59, 'add', NULL, 'Estagios', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (60, 'delete', NULL, 'Estagios', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (61, 'Comissoes', NULL, 'Comissoes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (62, 'edit', NULL, 'Comissoes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (63, 'add', NULL, 'Comissoes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (64, 'delete', NULL, 'Comissoes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (65, 'Usuarios', NULL, 'Usuarios', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (66, 'edit', NULL, 'Usuarios', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (67, 'add', NULL, 'Usuarios', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (68, 'delete', NULL, 'Usuarios', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (69, 'Pacientes Acompanhamentos', NULL, 'PacientesAcompanhamentos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (70, 'edit', NULL, 'PacientesAcompanhamentos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (71, 'add', NULL, 'PacientesAcompanhamentos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (72, 'delete', NULL, 'PacientesAcompanhamentos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (73, 'Sexos', NULL, 'Sexos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (74, 'edit', NULL, 'Sexos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (75, 'add', NULL, 'Sexos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (76, 'delete', NULL, 'Sexos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (77, 'Comissoes Correcoes', NULL, 'ComissoesCorrecoes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (78, 'edit', NULL, 'ComissoesCorrecoes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (79, 'add', NULL, 'ComissoesCorrecoes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (80, 'delete', NULL, 'ComissoesCorrecoes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (81, 'Pacientes Emergencias', NULL, 'PacientesEmergencias', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (82, 'edit', NULL, 'PacientesEmergencias', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (83, 'add', NULL, 'PacientesEmergencias', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (84, 'delete', NULL, 'PacientesEmergencias', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (85, 'Especialidades', NULL, 'Especialidades', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (86, 'edit', NULL, 'Especialidades', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (87, 'add', NULL, 'Especialidades', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (88, 'delete', NULL, 'Especialidades', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (89, 'Conselhos', NULL, 'Conselhos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (90, 'edit', NULL, 'Conselhos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (91, 'add', NULL, 'Conselhos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (92, 'delete', NULL, 'Conselhos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (93, 'Tabelas Valores', NULL, 'TabelasValores', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (94, 'edit', NULL, 'TabelasValores', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (95, 'add', NULL, 'TabelasValores', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (96, 'delete', NULL, 'TabelasValores', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (97, 'Tabelas Precos', NULL, 'TabelasPrecos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (98, 'edit', NULL, 'TabelasPrecos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (99, 'add', NULL, 'TabelasPrecos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (100, 'delete', NULL, 'TabelasPrecos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (101, 'Servicos Clinicas', NULL, 'ServicosClinicas', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (102, 'edit', NULL, 'ServicosClinicas', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (103, 'add', NULL, 'ServicosClinicas', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (104, 'delete', NULL, 'ServicosClinicas', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (105, 'Contatos', NULL, 'Contatos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (106, 'edit', NULL, 'Contatos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (107, 'add', NULL, 'Contatos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (108, 'delete', NULL, 'Contatos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (109, 'Pacientes Convenios', NULL, 'PacientesConvenios', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (110, 'edit', NULL, 'PacientesConvenios', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (111, 'add', NULL, 'PacientesConvenios', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (112, 'delete', NULL, 'PacientesConvenios', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (113, 'Profissoes', NULL, 'Profissoes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (114, 'edit', NULL, 'Profissoes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (115, 'add', NULL, 'Profissoes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (116, 'delete', NULL, 'Profissoes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (117, 'Tabelas Reajustes', NULL, 'TabelasReajustes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (118, 'edit', NULL, 'TabelasReajustes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (119, 'add', NULL, 'TabelasReajustes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (120, 'delete', NULL, 'TabelasReajustes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (121, 'Menus', NULL, 'Menus', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (122, 'edit', NULL, 'Menus', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (123, 'add', NULL, 'Menus', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (124, 'delete', NULL, 'Menus', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (125, 'Classificacoes', NULL, 'Classificacoes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (126, 'edit', NULL, 'Classificacoes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (127, 'add', NULL, 'Classificacoes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (128, 'delete', NULL, 'Classificacoes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (129, 'Prestadores', NULL, 'Prestadores', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (130, 'edit', NULL, 'Prestadores', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (131, 'add', NULL, 'Prestadores', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (132, 'delete', NULL, 'Prestadores', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (133, 'Pacientes Midias', NULL, 'PacientesMidias', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (134, 'edit', NULL, 'PacientesMidias', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (135, 'add', NULL, 'PacientesMidias', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (136, 'delete', NULL, 'PacientesMidias', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (137, 'Pacientes Servicos', NULL, 'PacientesServicos', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (138, 'edit', NULL, 'PacientesServicos', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (139, 'add', NULL, 'PacientesServicos', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (140, 'delete', NULL, 'PacientesServicos', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (141, 'Midias', NULL, 'Midias', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (142, 'edit', NULL, 'Midias', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (143, 'add', NULL, 'Midias', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (144, 'delete', NULL, 'Midias', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (145, 'Pacientes', NULL, 'Pacientes', 'index', 1, 1, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (146, 'edit', NULL, 'Pacientes', 'edit', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (147, 'add', NULL, 'Pacientes', 'add', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
INSERT IGNORE INTO `menus` (`id`, `titulo`, `path`, `controller`, `action`, `status`, `item_menu`, `icon`, `created`, `modified`) VALUES  (148, 'delete', NULL, 'Pacientes', 'delete', 1, 0, NULL, '2016-09-17 01:21:38', NULL);
/*!40000 ALTER TABLE `menus` ENABLE KEYS */;
UNLOCK TABLES;
-- Fim dos daddos da tabela `menus` --


-- Inicio dos daddos da tabela `usuarios` --
LOCK TABLES `usuarios` WRITE;
/*!40000 ALTER TABLE `usuarios` DISABLE KEYS */;
INSERT IGNORE INTO `usuarios` (`id`, `nome`, `login`, `senha`, `status`, `created`, `modified`) VALUES  (1, 'Super Administrador do Sistema', 'super', '$2y$10$n.8Orp5K3Y7OS3ZqI8dOsuxTN6Ujn0rxYGzmJdBRvvNnbgJLicbRq', 1, '2016-09-17 01:21:38', NULL);
/*!40000 ALTER TABLE `usuarios` ENABLE KEYS */;
UNLOCK TABLES;
-- Fim dos daddos da tabela `usuarios` --

